name: Release Nyx App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          choco install curl unzip 7zip

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './client/src-tauri -> target'

      - name: Download and extract fingerprint browser
        run: |
          echo "Downloading fingerprint browser..."
          node client/scripts/download-browser-gha.cjs

      - name: Install frontend dependencies
        run: pnpm install
        working-directory: ./client

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: './client'
          tagName: ${{ github.ref_name }}
          releaseName: "Nyx Crawler Bot ${{ github.ref_name }}"
          releaseBody: |
            ## What's Changed
            - See the assets below to download and install this version
            - Auto-update will be available for existing installations
            
            ## Installation
            - **Windows**: Download and run the `.msi` installer
            
            ## Security
            All releases are code-signed and verified.
          releaseDraft: true
          prerelease: false
          includeDebug: false
          includeRelease: true