name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          choco install curl unzip 7zip

      - name: Install dependencies (macos only)
        if: matrix.platform == 'macos-latest'
        run: |
          brew install curl unzip p7zip

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './client/src-tauri -> target'

      - name: Download and extract fingerprint browser
        run: |
          echo "Starting browser download..."
          node client/scripts/download-browser-gha.cjs
          echo "Browser download completed. Checking for files:"
          ls -la chrome.exe || echo "chrome.exe not found"
          ls -la itbrowser_fingerprint.exe || echo "itbrowser_fingerprint.exe not found"
          ls -la fingerprint_browser_v1.0.7z || echo "fingerprint_browser_v1.0.7z found"

      - name: Install frontend dependencies
        run: pnpm install
        working-directory: ./client

      - name: Build frontend
        run: pnpm build
        working-directory: ./client

      - name: Install backend dependencies
        run: pnpm install
        working-directory: ./server

      - name: Verify build directory
        run: |
          echo "Checking build directory contents:"
          ls -la client/src-tauri/target/release/
        if: matrix.platform == 'windows-latest' || matrix.platform == 'macos-latest'

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./client
          tagName: ${{ github.ref_name }}
          releaseName: "Nyx Crawler Bot v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          includeDebug: false
          includeRelease: true
          includeDebug: false
          includeRelease: true