name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf curl unzip p7zip-full

      - name: Install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          choco install curl unzip 7zip

      - name: Install dependencies (macos only)
        if: matrix.platform == 'macos-latest'
        run: |
          brew install curl unzip p7zip

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './client/src-tauri -> target'

      - name: Download and extract fingerprint browser
        run: |
          node client/scripts/download-browser-gha.cjs

      - name: Install frontend dependencies
        run: pnpm install
        working-directory: ./client

      - name: Build frontend
        run: pnpm build
        working-directory: ./client

      - name: Install backend dependencies
        run: pnpm install
        working-directory: ./server

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./client
          tagName: ${{ github.ref_name }}
          releaseName: "Nyx Crawler Bot v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false